version: "3.9"

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/data

  embedding_service:
    build: ./embedding_service
    container_name: embedding_service
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - chromadb

  vector:
    image: timberio/vector:latest-debian
    container_name: vector
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      - embedding_service

volumes:
  chroma_data:
